drop database takenlijst;
create database takenlijst;
USE takenlijst;
CREATE TABLE USERS (
	ID integer NOT NULL AUTO_INCREMENT, 
    USERNAME varchar (35) NOT NULL,
	WACHTWOORD varchar (15) NOT NULL,
    FIRSTNAME varchar (20) NOT NULL,
    LASTNAME varchar (35) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IDX_USERNAME ON USERS (USERNAME);

CREATE TABLE CATEGORIE (
	CATID integer NOT NULL AUTO_INCREMENT,
    ID integer NOT NULL,
    CATNAME varchar (50) NOT NULL,
    PRIMARY KEY (CATID),
    FOREIGN KEY (ID) REFERENCES USERS(ID)
);

CREATE TABLE TAAK (
	TAAKID integer NOT NULL AUTO_INCREMENT,
	PARENTCATIDT integer,
    TITEL varchar (50),
    STARTDAT varchar(10),
    EINDDAT varchar(10),
	TAAKOMSCHR varchar (150),
    PRIMARY KEY (TAAKID),
    FOREIGN KEY (PARENTCATIDT) REFERENCES CATEGORIE(CATID)
    ON DELETE CASCADE
);

CREATE TABLE SUBCATEGORIE (
	SUBCATID integer NOT NULL,
    PARENTCATIDC integer,
    PRIMARY KEY (SUBCATID),
    FOREIGN KEY (PARENTCATIDC) REFERENCES CATEGORIE(CATID)
    ON DELETE CASCADE
);

INSERT INTO `takenlijst`.`users` (`USERNAME`, `WACHTWOORD`, `FIRSTNAME`, `LASTNAME`) VALUES ('joske', 'joske', 'joske', 'vermeulen');

SELECT c.ID, c.CATID, c.CATNAME, s.PARENTCATIDC, t.TAAKID, t.PARENTCATIDT, t.TITEL, t.TAAKOMSCHR 
FROM CATEGORIE c 
LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID 
LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID 
ORDER BY ID,CATNAME;

SELECT c.ID, c.CATID, c.CATNAME, s.PARENTCATIDC, t.TAAKID, t.PARENTCATIDT, t.TITEL, t.TAAKOMSCHR FROM CATEGORIE c LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID ORDER BY ID,CATNAME;


-- Taak verwijderen
SELECT *
FROM TAAK
WHERE TAAKID= 5;

DELETE FROM TAAK WHERE TAAKID = ?;

-- categorie verwijderen
SELECT *
FROM TAAK
WHERE PARENTCATIDT= 7;

DELETE FROM TAAK WHERE PARENTCATIDT= ?;

SELECT *
FROM CATEGORIE
WHERE CATID= 7;

DELETE FROM CATEGORIE WHERE CATID= ?;

-- Taak updaten
UPDATE TAAK
SET TITEL = "taak3", TAAKOMSCHR = "omschrijving3"
WHERE TAAKID= 1;

UPDATE TAAK SET TITEL = ?, TAAKOMSCHR = ? WHERE TAAKID= ?;

-- Categorie updaten
UPDATE CATEGORIE
SET CATNAME = "Javascript"
WHERE CATID= 6;

UPDATE CATEGORIE SET CATNAME = ? WHERE CATID= ?;

-- Array vullen om te deleten

SELECT DISTINCT c.CATID
FROM CATEGORIE c 
LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID 
LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID 
WHERE PARENTCATIDC = 16;

SELECT DISTINCT c.CATID FROM CATEGORIE c LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID WHERE PARENTCATIDC = ?;

SELECT c.CATID, s.PARENTCATIDC
FROM CATEGORIE c 
LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID 
LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID 
WHERE PARENTCATIDC = 16;

DELETE FROM CATEGORIE WHERE CATID=24; 
DELETE FROM CATEGORIE WHERE CATID NOT IN  (SELECT SUBCATID FROM SUBCATEGORIE); 
DELETE FROM SUBCATEGORIE WHERE SUBCATID=24;

SELECT * FROM users;
SELECT * FROM categorie;
SELECT * FROM taak;
Select * FROM subcategorie;

SELECT c.ID, c.CATID, c.CATNAME, s.PARENTCATIDC, t.TAAKID, t.PARENTCATIDT, t.TITEL, t.STARTDAT, t.EINDDAT, t.TAAKOMSCHR FROM CATEGORIE c LEFT OUTER JOIN SUBCATEGORIE s ON s.SUBCATID = c.CATID LEFT OUTER JOIN TAAK t ON t.PARENTCATIDT = c.CATID ORDER BY ID,CATNAME;